// @polsia:user-owned — operator domain contracts.
//
// The Operator is an agent that *uses* the deterministic engines; it is not one
// of them. These schemas describe what a person asks it for, what it is allowed
// to do while answering, and what it hands back. They are isomorphic — no
// database, no provider, no `server-only`, no clock — for the same reason every
// other contract module in this product is: the route that serves an operator
// run and the page that renders it share one schema, so a field cannot be added
// on one side and missed on the other, and a client cannot be shown a shape the
// server never produces.
//
// Two invariants run through this file, and they are the whole point of it:
//
//   1. Every number in a trust report is produced by an engine, never by a
//      model. The report contract therefore carries references (run ids,
//      scenario ids, decision ids) beside its figures, so a reader can go and
//      look at the evidence rather than take the operator's word for it.
//
//   2. The operator's own words are never evidence. The one free-text field the
//      model may fill — `interpretation` — is a separate field from every
//      measured one, and it is labelled as interpretation wherever it is shown.
//      Nothing the model types can reach a field that is rendered as a
//      measurement.

import { z } from 'zod';
import { AgentCandidate } from '@/lib/contracts/agents';
import { SimulationScenarioIdentity } from '@/lib/contracts/simulation';
import { EvaluationResult } from '@/lib/evaluation/types';

/** Versions are small integers assigned by hand, never timestamps. */
export const OPERATOR_POLICY_VERSION = 1;

/**
 * What the operator is allowed to do.
 *
 * `preview` is a genuine mode rather than a flag on a full run: the execution
 * tool is not in the tool list at all, so a model cannot talk its way into a
 * benchmark by arguing that the objective implies one. A preview costs one
 * bounded model invocation and no provider-driven simulation.
 *
 * `execute` additionally requires the fingerprint of the plan a human was shown,
 * so the authorisation a person gave covers the exact execution that follows
 * rather than a category of execution.
 */
export const OPERATOR_MODES = ['preview', 'execute'] as const;
export const OperatorMode = z.enum(OPERATOR_MODES);
export type OperatorMode = z.infer<typeof OperatorMode>;

/**
 * What a caller may ask for. Nothing executable, and nothing identifying.
 *
 * There is no owner field, no run id and no tool list here, because a request
 * that could name any of those would be a request that could name someone
 * else's. Identity is resolved from the authenticated session, the tool surface
 * is fixed by the server, and the runs a session may read are the runs that
 * session's own execution produced.
 */
export const OperatorRunRequest = z.object({
  /** Plain language. The operator decides what to do about it; it is not a command. */
  objective: z.string().min(8).max(1000),
  /**
   * The agent to test, as a catalogue key. Omitted, the operator is left to
   * choose — and told to, rather than being handed a silent default.
   */
  agentKey: z.string().min(1).max(200).nullable().optional(),
  mode: OperatorMode.default('preview'),
  /**
   * Required in `execute` mode: the fingerprint of the plan the caller was
   * shown. The server recomputes it after the operator has committed to a plan
   * and refuses the run when the two disagree.
   */
  authorizedPlanFingerprint: z.string().min(1).max(128).nullable().optional(),
});
export type OperatorRunRequest = z.infer<typeof OperatorRunRequest>;

/**
 * The phases a tool call belongs to, in the order a run normally moves through
 * them. The phase is assigned by the server from a declared table, never by the
 * model, so the trace a reader sees is a record of what happened rather than a
 * story about it.
 */
export const OPERATOR_PHASES = [
  'understand',
  'discover',
  'plan',
  'execute',
  'inspect',
  'analyze',
  'report',
] as const;
export const OperatorPhase = z.enum(OPERATOR_PHASES);
export type OperatorPhase = z.infer<typeof OperatorPhase>;

/**
 * How a tool call ended.
 *
 * `refused` is deliberately distinct from `failed`. A refusal is the boundary
 * working — the operator asked for something it is not permitted to do, and the
 * tool said so — and a reader needs to be able to tell that apart from a tool
 * that broke. Neither is ever hidden: a run whose tool calls were refused says
 * so in its state and in its report.
 */
export const OPERATOR_TOOL_STATUSES = ['completed', 'refused', 'failed'] as const;
export const OperatorToolStatus = z.enum(OPERATOR_TOOL_STATUSES);
export type OperatorToolStatus = z.infer<typeof OperatorToolStatus>;

/**
 * One recorded tool call.
 *
 * `summary` is generated by the tool itself from the structured result it just
 * produced — never by the model. That is what makes the trace trustworthy: the
 * line a reader sees beside "run_benchmark" was written by the code that ran the
 * benchmark, from the numbers it returned.
 *
 * There is no field for the model's reasoning, and there will not be one. The
 * operator's closing narration is a single labelled field on the run state; the
 * trace records actions.
 */
export const OperatorTraceStep = z.object({
  index: z.number().int().nonnegative(),
  phase: OperatorPhase,
  tool: z.string().min(1).max(64),
  status: OperatorToolStatus,
  /** One line, written by the tool from its own structured result. */
  summary: z.string().min(1).max(400),
  /**
   * A bounded, structured echo of what the tool returned. Size-capped by the
   * recorder, so a trace cannot become a second copy of the evidence.
   */
  detail: z.record(z.string(), z.unknown()).default({}),
  /** Generated at the boundary, when the call returned. */
  at: z.string().datetime(),
});
export type OperatorTraceStep = z.infer<typeof OperatorTraceStep>;

/**
 * The plan the operator committed to, before anything ran.
 *
 * Every field is copied from the benchmark registry or the agent catalogue. The
 * plan exists so that the two things a reader most needs to check — *what* will
 * run and *what it will cost* — are decided before execution rather than
 * discovered afterwards, and so that the authorisation a person gives is given
 * against a specific, fingerprinted description.
 */
export const OperatorTestPlan = z.object({
  /** The objective, echoed — the plan is a plan for *this* request. */
  objective: z.string().min(1),
  benchmark: z.object({
    id: z.string().min(1),
    version: z.number().int().positive(),
    name: z.string().min(1),
    environmentKey: z.string().min(1),
    objectiveKey: z.string().min(1),
  }),
  agent: z.object({
    key: z.string().min(1),
    identity: z.string().min(1),
    provider: z.string().min(1),
    model: z.string().min(1),
    providerLabel: z.string().min(1),
    isDeploymentDefault: z.boolean(),
  }),
  /** The conditions, in matrix order, from the registry definition. */
  scenarios: z.array(
    z.object({
      id: z.string().min(1),
      version: z.number().int().positive(),
      isBaseline: z.boolean(),
    }),
  ),
  seeds: z.array(z.number().int().min(0)),
  caseCount: z.number().int().positive(),
  /** Cases this execution will drive a real agent turn loop through. */
  providerDrivenSimulations: z.number().int().nonnegative(),
  /** What the whole execution is bounded by. See `config.ts` for why each value. */
  bounds: z.object({
    maxTurns: z.number().int().positive(),
    maxToolCalls: z.number().int().positive(),
    maxBenchmarkRuns: z.number().int().positive(),
    maxCounterfactualAnalyses: z.number().int().positive(),
    maxDurationMs: z.number().int().positive(),
  }),
  /** Stable digest of the fields above. What an execution authorisation covers. */
  fingerprint: z.string().min(1).max(128),
});
export type OperatorTestPlan = z.infer<typeof OperatorTestPlan>;

/**
 * The benchmark result, reduced to what an operator needs and a reader can scan.
 *
 * This is a projection of `BenchmarkResult`, not a second aggregation: every
 * field is copied from the engine's own output. What it leaves out is the bulk —
 * full per-case evaluations and full traces — which the operator fetches one at
 * a time, deliberately, when it decides a case is worth looking at.
 */
export const OperatorResultSlice = z.object({
  benchmark: z.object({
    id: z.string().min(1),
    version: z.number().int().positive(),
    name: z.string().min(1),
  }),
  agent: z.object({
    provider: z.string().min(1),
    model: z.string().min(1),
    label: z.string().nullable(),
  }),
  caseSummary: z.record(z.string(), z.number().int().nonnegative()),
  dimensions: z.record(z.string(), z.number().nullable()),
  robustness: z.record(z.string(), z.unknown()),
  scenarios: z.array(z.record(z.string(), z.unknown())),
  failures: z.record(z.string(), z.unknown()),
  /** Every run the execution created, in matrix order. The evidence index. */
  runs: z.array(
    z.object({
      caseKey: z.string().min(1),
      scenarioId: z.string().min(1),
      scenarioVersion: z.number().int().positive(),
      seed: z.number().int().min(0),
      isBaseline: z.boolean(),
      runId: z.string().min(1),
      status: z.string().min(1),
      outcome: z.string().min(1),
      terminationReason: z.string().nullable(),
      overallScore: z.number().nullable(),
    }),
  ),
});
export type OperatorResultSlice = z.infer<typeof OperatorResultSlice>;

/** One case's run, as the operator sees it after asking for it by name. */
export const OperatorCaseEvidence = z.object({
  runId: z.string().min(1),
  caseKey: z.string().min(1),
  scenario: SimulationScenarioIdentity.nullable(),
  seed: z.number().int().min(0),
  status: z.string().min(1),
  terminationReason: z.string().nullable(),
  /** Produced by the evaluation engine from this run's persisted evidence. */
  evaluation: EvaluationResult,
  actions: z.object({
    total: z.number().int().nonnegative(),
    accepted: z.number().int().nonnegative(),
    rejected: z.number().int().nonnegative(),
    /** The rejected attempts themselves, bounded and summarised. */
    rejectedActions: z.array(
      z.object({
        step: z.number().int().nonnegative(),
        type: z.string().min(1),
        reason: z.string().nullable(),
      }),
    ),
  }),
  toolCalls: z.object({
    total: z.number().int().nonnegative(),
    failed: z.number().int().nonnegative(),
    failedNames: z.array(z.string()),
  }),
  faults: z.array(z.string()),
});
export type OperatorCaseEvidence = z.infer<typeof OperatorCaseEvidence>;

/**
 * What a counterfactual analysis contributes to a readiness judgement.
 *
 * A projection of the counterfactual engine's report, carrying the engine's own
 * policy names and its own regret ranking. `criticalDecision` is the engine's
 * ranking put first — the operator selects which run to analyse, never which
 * decision was most costly.
 */
export const OperatorCounterfactualFinding = z.object({
  runId: z.string().min(1),
  caseKey: z.string().min(1),
  scenarioId: z.string().nullable(),
  /** The engine's declared policies, echoed so a reader sees what was held constant. */
  policies: z.record(z.string(), z.string()),
  baselineOverallScore: z.number(),
  decisionsAnalysed: z.number().int().nonnegative(),
  improvingDecisions: z.number().int().nonnegative(),
  worseningDecisions: z.number().int().nonnegative(),
  uncontestedDecisions: z.number().int().nonnegative(),
  outcomeFlipDecisions: z.number().int().nonnegative(),
  maxRegret: z.number().nullable(),
  meanRegret: z.number().nullable(),
  criticalDecision: z
    .object({
      index: z.number().int().nonnegative(),
      step: z.number().int().nonnegative(),
      actionId: z.string().min(1),
      actionType: z.string().min(1),
      regret: z.number(),
      recordedOverall: z.number(),
      bestAlternativeOverall: z.number().nullable(),
      statement: z.string().min(1),
    })
    .nullable(),
});
export type OperatorCounterfactualFinding = z.infer<typeof OperatorCounterfactualFinding>;

/**
 * One rule the readiness verdict was reached by.
 *
 * A verdict is only as good as its rules, so every rule is published: what it
 * measured, the threshold it was compared against, and the value it actually
 * saw. A rule whose evidence was absent records `observed: null` and an outcome
 * of `insufficient` — never a zero, and never a silent omission.
 */
export const READINESS_RULE_OUTCOMES = ['pass', 'caution', 'fail', 'insufficient'] as const;
export const ReadinessRuleOutcome = z.enum(READINESS_RULE_OUTCOMES);
export type ReadinessRuleOutcome = z.infer<typeof ReadinessRuleOutcome>;

export const ReadinessRule = z.object({
  id: z.string().min(1),
  /** What the rule is about, in a reader's words. */
  label: z.string().min(1),
  /** The threshold, written out, so the verdict can be argued with. */
  threshold: z.string().min(1),
  /** The measured value as text, or `null` when the evidence did not support one. */
  observed: z.string().nullable(),
  outcome: ReadinessRuleOutcome,
  /**
   * True when a failure of this rule decides the verdict on its own. Only two
   * rules are decisive, and `readiness.ts` explains why each one is.
   */
  decisive: z.boolean(),
  detail: z.string().min(1),
  /** Where to look. Run ids, scenario ids, metric names — never a paraphrase. */
  evidence: z.array(z.string()),
});
export type ReadinessRule = z.infer<typeof ReadinessRule>;

/**
 * The four verdicts, and what each one claims.
 *
 * `INSUFFICIENT_EVIDENCE` is a verdict rather than an error. A deployment
 * question that the evidence cannot answer has an answer — "not from this" —
 * and returning it is more useful than returning a cautious-sounding number
 * derived from nothing.
 */
export const READINESS_VERDICTS = [
  'READY',
  'CAUTION',
  'NOT_READY',
  'INSUFFICIENT_EVIDENCE',
] as const;
export const ReadinessVerdict = z.enum(READINESS_VERDICTS);
export type ReadinessVerdict = z.infer<typeof ReadinessVerdict>;

export const ReadinessAssessment = z.object({
  verdict: ReadinessVerdict,
  /** One sentence stating the verdict and the rule that produced it. */
  headline: z.string().min(1),
  /** The named methodology this assessment was computed by. */
  methodology: z.string().min(1),
  /** Every rule considered, in evaluation order, including the ones that passed. */
  rules: z.array(ReadinessRule),
});
export type ReadinessAssessment = z.infer<typeof ReadinessAssessment>;

/**
 * The Agent Trust Report.
 *
 * Assembled by `report.ts` from the recorded tool results. The model cannot
 * write any measured field: it may supply `interpretation`, which is labelled as
 * the operator's reading and rendered apart from every figure.
 */
export const TrustReport = z.object({
  policyVersion: z.number().int().positive(),
  objective: z.string().min(1),
  target: z.object({
    key: z.string().min(1),
    identity: z.string().min(1),
    provider: z.string().min(1),
    model: z.string().min(1),
    providerLabel: z.string().min(1),
  }),
  benchmark: z.object({
    id: z.string().min(1),
    version: z.number().int().positive(),
    name: z.string().min(1),
    environmentKey: z.string().min(1),
    objectiveKey: z.string().min(1),
    scenarios: z.array(SimulationScenarioIdentity),
    seeds: z.array(z.number().int().min(0)),
    caseCount: z.number().int().positive(),
  }),
  /** Observed facts, each already labelled with where it came from. */
  observed: z.object({
    overall: z.number().nullable(),
    minimum: z.number().nullable(),
    maximum: z.number().nullable(),
    categories: z.record(z.string(), z.number().nullable()),
    robustness: z.object({
      formula: z.string().min(1),
      score: z.number().nullable(),
      baselineScore: z.number().nullable(),
      worstDegradation: z.number().nullable(),
      greatestDegradationScenarioId: z.string().nullable(),
      worstScenarioId: z.string().nullable(),
      unavailableReason: z.string().nullable(),
    }),
    caseSummary: z.record(z.string(), z.number().int().nonnegative()),
    scenarioPerformance: z.array(
      z.object({
        scenarioId: z.string().min(1),
        scenarioVersion: z.number().int().positive(),
        isBaseline: z.boolean(),
        score: z.number().nullable(),
        retention: z.number().nullable(),
        absoluteDegradation: z.number().nullable(),
        caseCount: z.number().int().nonnegative(),
        evaluatedCount: z.number().int().nonnegative(),
        runStatus: z.string().nullable(),
      }),
    ),
    failures: z.array(
      z.object({
        category: z.string().min(1),
        count: z.number().int().nonnegative(),
        metric: z.string().nullable(),
        runIds: z.array(z.string()),
        scenarioIds: z.array(z.string()),
      }),
    ),
    counterfactuals: z.array(OperatorCounterfactualFinding),
  }),
  verdict: ReadinessAssessment,
  /** The operator's reading of the evidence. Never a measurement. */
  interpretation: z.string().nullable(),
  /** The closing narrative the model produced, kept separate from every figure. */
  recommendation: z.string().nullable(),
  /** Every run the report was derived from. */
  evidence: z.object({
    runIds: z.array(z.string()),
    scenarioIds: z.array(z.string()),
    decisionIds: z.array(z.string()),
    /** Named formulas and policies the figures were computed under. */
    policies: z.array(z.object({ name: z.string().min(1), value: z.string().min(1) })),
  }),
  provenance: z.object({
    /** True when the operator committed to a plan before executing. */
    planFingerprint: z.string().nullable(),
    benchmarkRuns: z.number().int().nonnegative(),
    counterfactualAnalyses: z.number().int().nonnegative(),
    toolCalls: z.number().int().nonnegative(),
    turns: z.number().int().nonnegative(),
    stopReason: z.string().min(1),
    generatedAt: z.string().datetime(),
  }),
});
export type TrustReport = z.infer<typeof TrustReport>;

/**
 * How a run ended.
 *
 * `completed` means the operator stopped of its own accord; `limit-reached`
 * means a bound stopped it; `refused` means an authorisation or a boundary did;
 * `failed` means something broke. The distinction is kept because the operator's
 * report is trustworthy only if a reader knows how much of the work got done.
 */
export const OPERATOR_RUN_STATUSES = ['completed', 'limit-reached', 'refused', 'failed'] as const;
export const OperatorRunStatus = z.enum(OPERATOR_RUN_STATUSES);
export type OperatorRunStatus = z.infer<typeof OperatorRunStatus>;

/**
 * What one request consumed, measured against the bounds it was given.
 *
 * `toolCalls` counts every call the operator made; `refusedToolCalls` and
 * `failedToolCalls` are the subsets that did not complete. All three are
 * published because a run that stopped because a boundary fired is a different
 * thing from a run that finished, and a reader has to be able to tell.
 */
export const OperatorUsage = z.object({
  turns: z.number().int().nonnegative(),
  toolCalls: z.number().int().nonnegative(),
  refusedToolCalls: z.number().int().nonnegative(),
  failedToolCalls: z.number().int().nonnegative(),
  benchmarkRuns: z.number().int().nonnegative(),
  counterfactualAnalyses: z.number().int().nonnegative(),
  durationMs: z.number().int().nonnegative(),
});
export type OperatorUsage = z.infer<typeof OperatorUsage>;

/**
 * Everything one operator request produced.
 *
 * `notices` is where the run says what it could not do — a counterfactual budget
 * that ran out, a provider failure, an evidence set too thin to judge. An empty
 * notices list is a claim, so it is only empty when there is genuinely nothing
 * to report.
 */
export const OperatorRunState = z.object({
  mode: OperatorMode,
  status: OperatorRunStatus,
  objective: z.string().min(1),
  /** The Strands stop reason, verbatim: `endTurn`, `limitTurns`, … */
  stopReason: z.string().min(1),
  /** What the operator was asked for and what it actually has configured. */
  requestedAgentKey: z.string().nullable(),
  agents: z.array(AgentCandidate),
  /** Why no agent could be named, when none could. Safe text; never a credential. */
  configurationNotice: z.string().nullable(),
  limits: z.object({
    maxTurns: z.number().int().positive(),
    maxToolCalls: z.number().int().positive(),
    maxBenchmarkRuns: z.number().int().positive(),
    maxCounterfactualAnalyses: z.number().int().positive(),
    maxDurationMs: z.number().int().positive(),
  }),
  usage: OperatorUsage,
  /** The plan the operator committed to, or `null` when it never made one. */
  plan: OperatorTestPlan.nullable(),
  /** True when an execution was authorised and matched the plan's fingerprint. */
  authorized: z.boolean(),
  trace: z.array(OperatorTraceStep),
  result: OperatorResultSlice.nullable(),
  caseEvidence: z.array(OperatorCaseEvidence),
  counterfactuals: z.array(OperatorCounterfactualFinding),
  /** The deterministic report, present only once the operator has asked for one. */
  report: TrustReport.nullable(),
  /**
   * The operator's closing narration, as the model wrote it. Labelled as
   * narration wherever it is shown; it is not evidence and no figure is read
   * from it.
   */
  narration: z.string().nullable(),
  notices: z.array(z.string()),
});
export type OperatorRunState = z.infer<typeof OperatorRunState>;

/** The response body of `POST /api/operator`. */
export const OperatorRunEnvelope = z.object({ run: OperatorRunState });
export type OperatorRunEnvelope = z.infer<typeof OperatorRunEnvelope>;

export const OPERATOR_ERROR_CODES = [
  'INVALID_REQUEST',
  'NO_AGENT_CONFIGURED',
  'UNKNOWN_AGENT',
  'UNAUTHORIZED_MODE',
  'PLAN_MISMATCH',
  'PROVIDER_UNAVAILABLE',
  'OPERATOR_FAILED',
] as const;
export type OperatorErrorCode = (typeof OPERATOR_ERROR_CODES)[number];

/**
 * Raised when an operator request cannot be served.
 *
 * The codes are deliberately about the *request*, not about the agent under
 * test: a benchmark that failed is a finding the report carries, not an error
 * that stops the run.
 */
export class OperatorError extends Error {
  readonly code: OperatorErrorCode;

  constructor(code: OperatorErrorCode, message: string) {
    super(message);
    this.name = 'OperatorError';
    this.code = code;
  }
}
